In [2]:
import numpy as np

In [3]:
A = np.array([[2, -0.22, 1.08, 0.04], 
              [2.04, -6, -1.74, 0.9],
              [0.15, -0.3, 3, 0.51],
              [-0.12, 0.69, 0.36, 3]])
A

array([[ 2.  , -0.22,  1.08,  0.04],
       [ 2.04, -6.  , -1.74,  0.9 ],
       [ 0.15, -0.3 ,  3.  ,  0.51],
       [-0.12,  0.69,  0.36,  3.  ]])

In [4]:
b = np.array([-8, 6, -15, -6])
b

array([ -8,   6, -15,  -6])

In [13]:
g = np.array([b[i] / A[i, i] for i in range(4)])
g

array([-4., -1., -5., -2.])

In [11]:
B = np.array([[-A[i, j] / A[i, i] if i != j else 0 for j in range(4)] for i in range(4)])
B

array([[ 0.  ,  0.11, -0.54, -0.02],
       [ 0.34,  0.  , -0.29,  0.15],
       [-0.05,  0.1 ,  0.  , -0.17],
       [ 0.04, -0.23, -0.12,  0.  ]])

In [14]:
q = np.linalg.norm(B, np.inf)
q

np.float64(0.78)

In [15]:
#lap bat dong
x0 = np.array([5, 1, 3, -3])
k = 0
while k < 50:
    k += 1
    x =  B @ x0 + g
    e = q / (1 - q) * np.linalg.norm(x - x0, np.inf)
    x0 = x

    if e < 10**-6:
        print('Buoc', k, x, e)
        break
    print(k, x, e)

1 [-5.45 -0.62 -4.64 -2.39] 37.050000000000004
2 [-1.5148 -1.8659 -4.3832 -1.5186] 13.952072727272729
3 [-1.807949 -0.471694 -4.852688 -1.105451] 4.943094000000001
4 [-1.4093258  -0.37324079 -4.76884528 -1.38150578] 1.4133004363636343
5 [-1.43824992 -0.30343151 -4.73200181 -1.39826622] 0.2475056368909077
6 [-1.45013117 -0.32646438 -4.7207254  -1.41990053] 0.08166200669427234
7 [-1.45832136 -0.33701931 -4.71875679 -1.41643139] 0.037422023003110316
8 [-1.46061483 -0.3398545  -4.71999253 -1.4145676 ] 0.010052037055018621
9 [-1.46029668 -0.33999635 -4.72047822 -1.41385895] 0.002512462412977252
10 [-1.46006418 -0.33964103 -4.72062878 -1.41375532] 0.0012597643559366658
11 [-1.45994587 -0.33950277 -4.72062249 -1.41380968] 0.0004901832522076514
12 [-1.45993297 -0.33947252 -4.72060534 -1.4138375 ] 0.00010725023875377751
13 [-1.45993834 -0.33947729 -4.72059823 -1.413846  ] 3.013493155109873e-05
14 [-1.45994254 -0.33948245 -4.72059699 -1.41384597] 1.831231927426372e-05
15 [-1.45994377 -0.33948423

In [9]:
#seidel
x0 = np.array([3., -1., 2.])
k = 0
while k < 50:
    k += 1
    x =  x0.copy()

    for i in range(3):
        x[i] = B[i] @ x + g[i]
        
    e = np.linalg.norm(x - x0, np.inf)
    x0 = x

    if e < 10**-6:
        print('Buoc', k, x, e)
        break
    print(k, x, e)

1 [0.7   1.34  2.561] 2.34
2 [0.1102   1.10984  2.644436] 0.5898
3 [0.1959352  1.11029984 2.62735794] 0.08573519999999996
4 [0.19238164 1.11300474 2.62847438] 0.0035535647999999087
5 [0.19179345 1.11266381 2.62854088] 0.0005881803648000172
6 [0.19190903 1.11267363 2.62851924] 0.00011557714283519371
7 [0.19190176 1.1126765  2.62852112] 7.273401333968144e-06
Buoc 8 [0.19190127 1.11267603 2.62852115] 4.850239485876262e-07
