In [1]:
import numpy as np

In [5]:
A = np.array([[0, 3, 5],
              [4, 6, 6],
              [7, 6, 7]])

In [9]:
np.linalg.inv(A)

array([[-0.125     , -0.1875    ,  0.25      ],
       [-0.29166667,  0.72916667, -0.41666667],
       [ 0.375     , -0.4375    ,  0.25      ]])

In [10]:
X0 = np.array([[-0.1, -0.1,  0.25],
               [-0.2,  0.7, -0.41],
               [ 0.3, -0.4,  0.25]])

In [12]:
np.linalg.norm(np.eye(3) - A @ X0)

np.float64(0.8681013765684275)

In [ ]:
k = 0
X0 = np.array([[-0.1, -0.1,  0.25],
               [-0.2,  0.7, -0.41],
               [ 0.3, -0.4,  0.25]])
while k < 1_000:
    k += 1
    X = 2 * X0 - X0 @ A @ X0
    e = np.linalg.norm(X - X0)
    X0 = X
    if e < 10**-10:
        print('*', k, X, e)
        break
    print(k, X, e)

1 [[-0.14   -0.225   0.246 ]
 [-0.278   0.727  -0.4176]
 [ 0.36   -0.445   0.25  ]] 0.17244349799282077
2 [[-0.128572   -0.197272    0.2490136 ]
 [-0.2914688   0.7290112  -0.41670656]
 [ 0.37398    -0.43972     0.249796  ]] 0.03630613037592409
3 [[-0.12523446 -0.18814628  0.24993462]
 [-0.29167     0.72915728 -0.41666762]
 [ 0.37494642 -0.43764753  0.24998508]] 0.010029672797050873
4 [[-0.12500103 -0.18750283  0.24999971]
 [-0.29166668  0.72916663 -0.41666667]
 [ 0.37499977 -0.43750065  0.24999993]] 0.0007053424780486591
5 [[-0.125      -0.1875      0.25      ]
 [-0.29166667  0.72916667 -0.41666667]
 [ 0.375      -0.4375      0.25      ]] 3.0974467239022874e-06
* 6 [[-0.125      -0.1875      0.25      ]
 [-0.29166667  0.72916667 -0.41666667]
 [ 0.375      -0.4375      0.25      ]] 5.921579593491366e-11
