In [2]:
import numpy as np

In [3]:
X = np.array([[-0.7, -2.9],
              [1.7, -1.1],
              [-4.9, -2.9],
              [3.1, 1.5],
              [-1.3, 0.8]])

In [19]:
Y = np.array([7.1, 5.8, -3.1, -1., -8.7])

In [20]:
A = np.concatenate(
    (
        np.ones(shape = (len(X), 1)), #len(x) = so cot cua X
        X
    ), 
    axis = 1
)
A

array([[ 1. , -0.7, -2.9],
       [ 1. ,  1.7, -1.1],
       [ 1. , -4.9, -2.9],
       [ 1. ,  3.1,  1.5],
       [ 1. , -1.3,  0.8]])

In [21]:
A.T @ A

array([[ 5.  , -2.1 , -4.6 ],
       [-2.1 , 38.69, 17.98],
       [-4.6 , 17.98, 20.92]])

In [7]:
np.linalg.inv(A.T @ A) 

array([[ 0.26037082, -0.02076906,  0.07510198],
       [-0.02076906,  0.04469183, -0.04297786],
       [ 0.07510198, -0.04297786,  0.10125291]])

In [8]:
w = np.linalg.inv(A.T @ A) @ A.T @ Y
w

array([-2.54721599,  2.3985894 , -3.88546037])

In [27]:
print(w[0], "+", w[1], "*x1 +", w[2], "*x2")

-2.5472159947895237 + 2.3985894007952817 *x1 + -3.8854603729603707 *x2


In [28]:
Y_pred = A @ w
Y_pred

array([ 7.04160651,  5.8043924 , -3.03246898, -0.93977941, -8.77375051])

In [29]:
Y_pred - Y

array([-0.05839349,  0.0043924 ,  0.06753102,  0.06022059, -0.07375051])

In [18]:
MSE = np.mean((Y_pred - Y)**2)
print(1 / len(X) * np.linalg.norm(Y_pred - Y)**2)
MSE

0.0034110379816262547


np.float64(0.003411037981626254)

In [12]:
RMSE = np.sqrt(MSE)
RMSE

np.float64(0.05840409216507225)